"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a@oxb$5&6y_3*&vggs0h=_7t9vh0osjrjb$_4hox$-oir@ev!('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ['103.137.24.123', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [

    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employees'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_URL = '/static/'  # This should be set to the correct URL for serving static files
# This is important to tell Django where your static files are located
STATICFILES_DIRS = [BASE_DIR / 'static']

# Base url to serve media files
MEDIA_URL = '/media/'

# Path where media is stored'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {

    "site_title": "DHQ Kotli Admin",
    "site_header": "DHQ Hospital Kotli",
    "site_brand": "DHQ Kotli",
    "welcome_sign": "Welcome to DHQ Hospital Kotli Admin Portal",
    "copyright": "DHQ Hospital © 2024",
    "search_model": ["auth.User", "employees.Employee"],
    "show_ui_builder": False,


    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user-circle",
        "employees.Employee": "fas fa-user-md",
        "employees.Address": "fas fa-map-marker-alt",
        "employees.Employment": "fas fa-briefcase-medical",
        "employees.HealthDetails": "fas fa-heartbeat",
        "employees.WorkDetails": "fas fa-hospital",
    },

    # Top navigation bar (you can customize the appearance here)
    "topmenu_links": [
        {"name": "Home", "url": "admin:index",
            "permissions": ["auth.view_user"]},
        {"name": "Users", "url": "auth:user_changelist",
            "permissions": ["auth.view_user"]},
        {"name": "Employees", "url": "employees:employee_changelist"},
    ],

    # Custom navigation bar (useful for large apps)
    "usermenu_links": [
        {"name": "Profile", "url": "admin:auth_user_change", "new_window": False},
        {"model": "auth.user"}
    ],

    # Branding the logo
    # Provide your hospital logo image path here
    "site_logo": "img/logo.jpg",
    "site_logo_classes": "img-circle",

    # Themes and colors (you can change the theme and look)
    # Options: 'lux', 'cosmo', 'cyborg', 'simplex', 'slate', etc.
    "theme": "cosmo",
    "dark_mode_theme": "slate",  # Customize dark mode as well

    # Related modal options
    "related_modal_active": True,

    # Make your list view action buttons smaller or larger
    "actions_sticky_top": True,

    "custom_css": "css/admin_styles.css",
    "custom_js": None,

    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "employees"],

    # Keep things looking professional
    "navigation_expanded": True,
    "changeform_format": "tabs",

}
